plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = minecraft_version + "-" + mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

sourceSets {
    main {
        resources.srcDir 'src/generated/resources'
    }
}

repositories {
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/'
    }
    maven {
        name = 'JitPack'
        url = 'https://jitpack.io'
    }
    maven {
        name = "Shedaniel Maven"
        url = "https://maven.shedaniel.me"
    }
    maven {
        name = "Architectury Maven"
        url = "https://maven.architectury.dev/"
    }
    maven {
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = 'Nucleoid'
        url = 'https://maven.nucleoid.xyz/'
    }
}

configurations {
    clientRuntimeMods {
        canBeConsumed = false
        canBeResolved = true
        transitive = true
    }
    jeiRuntimeMods {
        canBeConsumed = false
        canBeResolved = true
        transitive = true
    }
    reiRuntimeMods {
        canBeConsumed = false
        canBeResolved = true
        transitive = true
    }
}

tasks.register('cleanClientRuntimeMods', Delete) {
    delete layout.projectDirectory.dir('run/client/mods')
}

tasks.register('cleanJeiRuntimeMods', Delete) {
    delete layout.projectDirectory.dir('run/jei/mods')
}

tasks.register('cleanReiRuntimeMods', Delete) {
    delete layout.projectDirectory.dir('run/rei/mods')
}

tasks.register('syncClientRuntimeMods', Sync) {
    dependsOn tasks.named('cleanClientRuntimeMods')
    from configurations.clientRuntimeMods
    into layout.projectDirectory.dir('run/client/mods')
}

tasks.register('syncJeiRuntimeMods', Sync) {
    dependsOn tasks.named('cleanJeiRuntimeMods')
    from configurations.jeiRuntimeMods
    into layout.projectDirectory.dir('run/jei/mods')
    include "gson-2*.jar"
    include "fastutil-*.jar"
    include "guava-*.jar"
    include "failureaccess-*.jar"
    include "listenablefuture-*.jar"
    include "jsr305-*.jar"
    include "checker-qual-*.jar"
    include "error_prone_annotations-*.jar"
    include "jei-${minecraft_version}-fabric-${jei_version}.jar"
}

tasks.register('syncReiRuntimeMods', Sync) {
    dependsOn tasks.named('cleanReiRuntimeMods')
    from configurations.reiRuntimeMods
    into layout.projectDirectory.dir('run/rei/mods')
    include "gson-2*.jar"
    include "fastutil-*.jar"
    include "guava-*.jar"
    include "failureaccess-*.jar"
    include "listenablefuture-*.jar"
    include "jsr305-*.jar"
    include "checker-qual-*.jar"
    include "error_prone_annotations-*.jar"
    include "RoughlyEnoughItems-fabric-${rei_version}.jar"
    include "architectury-fabric-*.jar"
    include "cloth-config-fabric-*.jar"
    include "basic-math-*.jar"
    include "error-notifier-fabric-*.jar"
}

loom {
    runs {
        client {
            client()
            runDir "run/client"
        }
        clientWithJei {
            client()
            runDir "run/jei"
        }
        clientWithRei {
            client()
            runDir "run/rei"
        }
        server {
            server()
            runDir "run/server"
        }
    }
}

fabricApi {
    configureDataGeneration {
        client = true
        outputDirectory = file("src/generated/resources")
    }
}

tasks.register('runData') {
    group = 'Fabric'
    description = 'Runs Fabric data generation.'
    dependsOn tasks.named('runDatagen')
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    compileOnly "com.terraformersmc:modmenu:${modmenu_version}"
    localRuntime "com.terraformersmc:modmenu:${modmenu_version}"
    compileOnly "dev.architectury:architectury-fabric:${architectury_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    jeiRuntimeMods "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${rei_version}"
    reiRuntimeMods "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
}

tasks.named('runClient') {
    dependsOn tasks.named('syncClientRuntimeMods')
}

tasks.named('runClientWithJei') {
    dependsOn tasks.named('syncJeiRuntimeMods')
}

tasks.named('runClientWithRei') {
    dependsOn tasks.named('syncReiRuntimeMods')
}

tasks.named('processResources', ProcessResources).configure {
    inputs.properties([
            mod_id            : mod_id,
            mod_name          : mod_name,
            mod_license       : mod_license,
            mod_version       : mod_version,
            mod_authors       : mod_authors,
            mod_description   : mod_description,
            minecraft_version : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            loader_version    : loader_version,
            modmenu_version   : modmenu_version
    ])

    filesMatching('fabric.mod.json') {
        expand inputs.properties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
