plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

def clientGeneratedResources = file('src/generated/client')
def serverGeneratedResources = file('src/generated/server')

sourceSets.main.resources.setSrcDirs([
        'src/main/resources',
        clientGeneratedResources,
        serverGeneratedResources
])
sourceSets.main.resources {
    exclude("**/*.bbmodel")
    exclude("**/.cache/**")
}

repositories {
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
}

neoForge {
    version = neo_version

    mods {
        create(mod_id) {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            gameDirectory = project.layout.projectDirectory.dir("run/${name}")
        }

        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArgument '--nogui'
        }

        serverData {
            serverData()
            programArguments.addAll(
                    '--mod', project.mod_id,
                    '--all',
                    '--output', serverGeneratedResources.getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientData {
            clientData()
            programArguments.addAll(
                    '--mod', project.mod_id,
                    '--all',
                    '--output', clientGeneratedResources.getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }
    }
}

dependencies {
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${jei_minecraft_version}-neoforge:${jei_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            curios_version_range   : curios_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register('runData') {
    group = 'NeoGradle/Runs tasks'
    description = 'Runs both clientData and serverData generation.'
    dependsOn tasks.named('runClientData'), tasks.named('runServerData')
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
