# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.2
minecraft_version_range=26.2

# Fabric
loom_version=1.17-SNAPSHOT
loader_version=0.19.3
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.1

# Dependencies
jei_version=30.2.0.18
rei_version=26.2.821
architectury_version=21.0.7

# Mod properties
mod_id=climbingclaws
mod_name=Climbing Claws
mod_license=MIT License
mod_version=1.3.0
mod_group_id=de.artemis.climbingclaws
mod_authors=DoomedArtemis
mod_description=Utility mod that adds hand-held Climbing Claws for wall and ceiling traversal, with enchantments and survival-friendly mobility.
