# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
minecraft_version=26.1
minecraft_version_range=[26.1,26.1.1)

# NeoForge
neo_version=26.1.0.19-beta
neo_version_range=[26.1.0-beta,26.1.1)
loader_version_range=[1,)

# Dependencies
jei_minecraft_version=26.1
jei_version=29.2.0.21
jei_version_range=[29.0.0,30.0.0)
curios_version=15.0.0-beta.1+26.1
curios_version_range=[15.0.0-beta.1,16.0.0)

# Mod properties
mod_id=climbingclaws
mod_name=Climbing Claws
mod_license=MIT License
mod_version=1.3r
mod_group_id=de.artemis.climbingclaws
mod_authors=DoomedArtemis
mod_description=Utility mod that adds hand-held Climbing Claws for wall and ceiling traversal, with enchantments and survival-friendly mobility.
