# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.76

# Dependencies
jei_minecraft_version=26.1.2
jei_version=29.14.0.43
curios_version=15.0.0+26.1.2

# Mod properties
mod_id=climbingclaws
mod_name=Climbing Claws
mod_license=MIT License
mod_version=1.2r
mod_group_id=de.artemis.climbingclaws
mod_authors=DoomedArtemis
mod_description=Utility mod that adds off-hand Climbing Claws for wall and ceiling traversal, with enchantments and survival-friendly mobility.
